pipeline {

    agent{
        label 'mac-sh'
    }

    when {
        anyOf {
            branch 'main'
            branch pattern: "PR-\\d+", comparator: "REGEXP"
        }
    }

    stages {
        stage("Build") {
            steps {
                script {
                    sh 'node --version'
                    sh 'npm --version'
                    sh 'npm install'
                    sh 'npm rebuild'
                }
            }
        }

        stage("blackducksca-security-scan") {
            steps {
                script {
                    security_scan blackducksca_scan_full: true, 
                                 blackducksca_waitForScan: true, 
                                 include_diagnostics: true, 
                                 mark_build_status: 'FAILURE', 
                                 product: 'blackducksca'
                }
            }
        }
    }

    
}
