name: Black Duck SCA Build Scan

on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]

jobs:
  blackduck-scan:
    runs-on: [ mac-arm-sh ]
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}/nodejs-npm

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Specify Node version
        cache: 'npm'
        cache-dependency-path: nodejs-npm/package-lock.json

    - name: Install dependencies
      run: npm install  # Use npm ci for faster, reliable installs

    - name: Build Project
      run: |
        npm run build --if-present

    - name: Black Duck SCA Build Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        detect_args: "--detect.source.path=${{ github.workspace }}/nodejs-npm --detect.npm.path='/Users/madhusud/.nvm/versions/node/v22.16.0/bin/npm' "
        
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
